-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 04:19:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ar3dex-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ar3dex-db
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `ar3dex-db`;
CREATE SCHEMA IF NOT EXISTS `ar3dex-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ar3dex-db` ;

-- -----------------------------------------------------
-- Table `ar3dex-db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar3dex-db`.`category` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ar3dex-db`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar3dex-db`.`productos` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(123) NOT NULL,
  `id_category` TINYINT NOT NULL,
  `price` DECIMAL(3,2) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL,
  `discount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_FK_1` (`id_category` ASC) VISIBLE,
  CONSTRAINT `category_FK_1`
    FOREIGN KEY (`id_category`)
    REFERENCES `ar3dex-db`.`category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ar3dex-db`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar3dex-db`.`administrador` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ar3dex-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar3dex-db`.`users` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(9) NULL DEFAULT NULL,
  `surname` VARCHAR(12) NULL DEFAULT NULL,
  `address` VARCHAR(40) NULL DEFAULT NULL,
  `city` VARCHAR(19) NULL DEFAULT NULL,
  `province` VARCHAR(6) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(19) NULL DEFAULT NULL,
  `email` VARCHAR(29) NULL DEFAULT NULL,
  `id_admin` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `admin_FK` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `admin_FK`
    FOREIGN KEY (`id_admin`)
    REFERENCES `ar3dex-db`.`administrador` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ar3dex-db`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar3dex-db`.`facturas` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `id_usuario` TINYINT NULL DEFAULT NULL,
  `fecha_factura` DATE NULL DEFAULT NULL,
  `direccion_de_facturacion` VARCHAR(40) NULL DEFAULT NULL,
  `ciudad_de_facturacion` VARCHAR(19) NULL DEFAULT NULL,
  `estado_o_provincia_de_facturacion` VARCHAR(6) NULL DEFAULT NULL,
  `codigo_postal_de_facturacion` VARCHAR(10) NULL DEFAULT NULL,
  `total` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `facturas_FK` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `facturas_FK`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ar3dex-db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ar3dex-db`.`items_de_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ar3dex-db`.`items_de_facturas` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `id_factura` SMALLINT NULL DEFAULT NULL,
  `id_producto` SMALLINT NULL DEFAULT NULL,
  `precio` DECIMAL(3,2) NULL DEFAULT NULL,
  `cantidad` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `items_de_facturas_FK` (`id_factura` ASC) VISIBLE,
  INDEX `items_de_facturas_FK_1` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `items_de_facturas_FK`
    FOREIGN KEY (`id_factura`)
    REFERENCES `ar3dex-db`.`facturas` (`id`),
  CONSTRAINT `items_de_facturas_FK_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ar3dex-db`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
